// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/13/2026, 1:55:12 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/opt/data/workspace/ngov-construct/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/opt/data/workspace/ngov-construct/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/opt/data/workspace/ngov-construct/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/opt/data/workspace/ngov-construct/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/opt/data/workspace/ngov-construct/plugins/**/*.{js,ts,mjs}","/opt/data/workspace/ngov-construct/composables/**/*.{js,ts,mjs}","/opt/data/workspace/ngov-construct/utils/**/*.{js,ts,mjs}","/opt/data/workspace/ngov-construct/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/opt/data/workspace/ngov-construct/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/opt/data/workspace/ngov-construct/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/opt/data/workspace/ngov-construct/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;