// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/16/2026, 8:19:26 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/ethan/Desktop/Apps/ngov-construct/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ethan/Desktop/Apps/ngov-construct/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ethan/Desktop/Apps/ngov-construct/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ethan/Desktop/Apps/ngov-construct/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ethan/Desktop/Apps/ngov-construct/app/plugins/**/*.{js,ts,mjs}","/Users/ethan/Desktop/Apps/ngov-construct/app/composables/**/*.{js,ts,mjs}","/Users/ethan/Desktop/Apps/ngov-construct/app/utils/**/*.{js,ts,mjs}","/Users/ethan/Desktop/Apps/ngov-construct/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ethan/Desktop/Apps/ngov-construct/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/ethan/Desktop/Apps/ngov-construct/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/ethan/Desktop/Apps/ngov-construct/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;