// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/13/2026, 5:18:29 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/opt/data/workspace/ngov-construct/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/opt/data/workspace/ngov-construct/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/opt/data/workspace/ngov-construct/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/opt/data/workspace/ngov-construct/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/opt/data/workspace/ngov-construct/app/plugins/**/*.{js,ts,mjs}","/opt/data/workspace/ngov-construct/app/composables/**/*.{js,ts,mjs}","/opt/data/workspace/ngov-construct/app/utils/**/*.{js,ts,mjs}","/opt/data/workspace/ngov-construct/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/opt/data/workspace/ngov-construct/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/opt/data/workspace/ngov-construct/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/opt/data/workspace/ngov-construct/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;